volumes:
  nginx_conf:

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - nginx_conf:/etc/nginx/conf.d:ro

  dockergen:
    image: nginxproxy/docker-gen
    command: -f /app/dockergen.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./app:/app
      - nginx_conf:/etc/nginx/conf.d

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.example
