upstream: docker-gen -watch -notify "nginx -s reload" "/app/upstream.tmpl;global.tmpl" /etc/nginx/conf.d/10-upstream.conf
dockergen: docker-gen -watch -notify "nginx -s reload" "/app/upstream.tmpl;global.tmpl" /etc/nginx/conf.d/default.conf
nginx: nginx -g "daemon off;"
